version: '3'

services:
  rethinkdb:
    image: rethinkdb:latest
    restart: always
    ports:
      - 28025:28015
    volumes:
      - ./data:/data

  app-fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - rethinkdb
    ports:
      - "8888:8000"
    networks:
      - app-fastapi

networks:
  app-fastapi:
    driver: bridge