version: '3'

services:
  rethinkdb:
    image: rethinkdb:latest
    restart: always
    ports:
      - 28026:28015
    volumes:
      - ./data:/data
    networks:
      - genikuiz

  app-fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    depends_on:
      - rethinkdb
    ports:
      - "3030:80"
    networks:
      - genikuiz

networks:
  genikuiz:
    driver: bridge