version: '3'

services:
  rethinkdb:
    image: rethinkdb:latest
    restart: always
    ports:
      - 28025:28015
    volumes:
      - ./data:/data
    networks:
      - genikuiz

  web:
    build: .
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    env_file:
      - .env
    depends_on:
      - rethinkdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - genikuiz

networks:
  genikuiz:
    driver: bridge